@/run/media/orclqq/Home/TMP_Zaher/adminoam/create_tables_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/create_sequences_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/ADMINoam_SYNONYMS.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/ADMINoam_GRANTS.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/insert_data_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/insert_data_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/insert_data_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/insert_data_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/insert_data_adminoam.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/V_OAM_STOCK_ITEMS.sql
@/run/media/orclqq/Home/TMP_Zaher/adminoam/V_OAM_STOCK_ITEMS_DETAILS
@/run/media/orclqq/Home/TMP_Zaher/adminoam/modifications.sql