
DROP VIEW V_OAM_STOCK_ITEMS;
--
CREATE VIEW V_OAM_STOCK_ITEMS AS  
select 
 t8.NUM_COMPANY
,t9.COD_PROJECT
--
,t5.NUM_ESTABLISHMENT
,t5.NAM_ESTABLISHMENT
--
,t8.NUM_DEPARTMENT
,t8.NAM_DEPARTMENT
,t7.NAM_SECTION
,t6.NUM_ITEM_CATEGORY
,t6.NAM_ITEM_CATEGORY
--
,t4.NUM_TYPE_MATERIAL
,t4.DES_TYPE_MATERIAL
--
,t1.NUM_PROJECT_ITEM ------ join with detail 
,t3.DES_ITEM
,sum(decode(IND_IN_OUT,'I',nvl(t1.VAL_ENTRY,0),'O',-1*nvl(t1.VAL_ENTRY,0))) Quantity_available
from
   OAM_STOCK_ITEMS    t1
  ,OAM_PROJECT_ITEMS  t2
  ,OAM_ITEMS          t3
  ,OAM_TYPES_MATERIAL t4
  ,COM_ESTABLISHMENTS t5
  ,OAM_ITEMS_CATEGORY  t6
  ,com_dep_sections t7
  ,COM_DEPARTMENTS t8
  ,ADMINCOR.COM_PROJECTS t9
where
        t1.NUM_PROJECT_ITEM   	= t2.NUM_PROJECT_ITEM
  and   t2.NUM_PROJECT          = t9.NUM_PROJECT
  and   t2.NUM_ITEM           	= t3.num_item
  and   t3.NUM_TYPE_MATERIAL  	= t4.NUM_TYPE_MATERIAL
  and   t1.NUM_ESTABLISHMENT  	= t5.NUM_ESTABLISHMENT
  and   t3.NUM_ITEM_CATEGORY   	= t6.NUM_ITEM_CATEGORY
  and   t6.NUM_DEP_SECTION     	= t7.NUM_DEP_SECTION
  and   t7.NUM_DEPARTMENT      	= t8.NUM_DEPARTMENT
group by 
 t8.NUM_COMPANY
,t9.COD_PROJECT
,t5.NUM_ESTABLISHMENT
,t5.NAM_ESTABLISHMENT
,t8.NUM_DEPARTMENT
,t8.NAM_DEPARTMENT
,t7.NAM_SECTION
,t6.NUM_ITEM_CATEGORY
,t6.NAM_ITEM_CATEGORY
,t4.NUM_TYPE_MATERIAL
,t4.DES_TYPE_MATERIAL
,t1.NUM_PROJECT_ITEM
,t3.DES_ITEM;

DROP public synonym V_OAM_STOCK_ITEMS;
create public synonym V_OAM_STOCK_ITEMS for V_OAM_STOCK_ITEMS;
grant select on V_OAM_STOCK_ITEMS TO ROLE_beyond_FULL;
--grant select on V_OAM_STOCK_ITEMS to ROLE_oem_full;

