
DROP VIEW V_OAM_STOCK_ITEMS_DETAILS;
--
CREATE VIEW V_OAM_STOCK_ITEMS_DETAILS AS  
select 
 t1.NUM_STOCK_ITEM
,t1.NUM_PROJECT_ITEM 
,T1.NUM_ESTABLISHMENT
,t1.IND_IN_OUT
,t1.VAL_ENTRY
,t3.NUM_QUOTATION
,t3.DES_QUOTATION
from
    OAM_STOCK_ITEMS       t1
   ,OAM_ITEM_QUOTATIONS   t2
   ,OAM_QUOTATIONS        t3
where
     t1.NUM_ITEM_QUOTATION  = t2.NUM_ITEM_QUOTATION(+)
and  t2.NUM_QUOTATION       = t3.NUM_QUOTATION(+);

DROP public synonym V_OAM_STOCK_ITEMS_DETAILS;
create public synonym V_OAM_STOCK_ITEMS_DETAILS for V_OAM_STOCK_ITEMS_DETAILS;
grant select on V_OAM_STOCK_ITEMS_DETAILS TO ROLE_beyond_FULL;
--grant select on V_OAM_STOCK_ITEMS_DETAILS to ROLE_oem_full;

