@/run/media/orclqq/Home/TMP_Zaher/AdminCor/create_tables_admincor.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/create_sequences_admincor.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/ADMINCOR_SYNONYMS.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/ADMINCOR_GRANTS.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/insert_data_admincor.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/Modifications.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/V_COM_COMPANIES.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/V_COM_DEP_SECTIONS.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/v_COM_DEPARTMENTS.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/V_COM_EMPLOYEES.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/V_COM_ESTABLISHMENTS.sql
@/run/media/orclqq/Home/TMP_Zaher/AdminCor/V_COM_TYPES_JOB_TITLE.sql
