ALTER TABLE COM_DEPARTMENTS  
MODIFY (COD_USER_RESPONSIBLE NUMBER );

ALTER TABLE COM_DEP_SECTIONS  
MODIFY (COD_USER_RESPONSIBLE NUMBER );

ALTER TABLE COM_DEPARTMENTS  
MODIFY (COD_USER_RESPONSIBLE NUMBER );

ALTER TABLE COM_DEP_SECTIONS  
MODIFY (COD_USER_RESPONSIBLE NUMBER );