-- USER SQL
CREATE USER admincor IDENTIFIED BY a
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO admincor;
GRANT "DBA" TO admincor ;
GRANT "CONNECT" TO admincor ;

-- USER SQL
CREATE USER adminsec IDENTIFIED BY a 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminsec ;
GRANT "DBA" TO adminsec ;
GRANT "CONNECT" TO adminsec ;

-- USER SQL
CREATE USER adminoam IDENTIFIED BY a 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminoam ;
GRANT "DBA" TO adminoam ;
GRANT "CONNECT" TO adminoam ;

-- USER SQL
CREATE USER adminret IDENTIFIED BY zaza#2014 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminret ;
GRANT "DBA" TO adminret ;
GRANT "CONNECT" TO adminret ;

-- USER SQL
CREATE USER adminwkf IDENTIFIED BY a
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminwkf ;
GRANT "DBA" TO adminwkf ;
GRANT "CONNECT" TO adminwkf ;

CREATE USER useronline IDENTIFIED BY braegy#2015 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminwkf ;
GRANT "CONNECT" TO adminwkf ;

CREATE USER userbatch IDENTIFIED BY a
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT "RESOURCE" TO adminwkf ;
GRANT "CONNECT" TO adminwkf ;


create role role_admincor_full;
create role role_adminsec_full;
create role role_adminret_full;
create role role_adminwkf_full;
create role role_adminoam_full;
create role role_batch_full;

grant  role_admincor_full to useronline;
grant  role_adminsec_full to useronline;
grant  role_adminret_full to useronline;
grant  role_adminwkf_full to useronline;
grant  role_adminoam_full to useronline;
grant  role_batch_full to userbatch;



CREATE SMALLFILE 
TABLESPACE TBS_ADMINcor_INDEXES_1M 
    DATAFILE '/u01/app/oracle/oradata/XE/DB_TBS_ADMINcor_INDEXES_1M' 
        SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE TBS_ADMINcor_TABLES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINcor_TABLES_1M' 
   SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
CREATE  BIGFILE TABLESPACE TBS_ADMINcor_INDEXES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINcor_INDEXES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE   BIGFILE TABLESPACE TBS_ADMINcor_TABLES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINcor_TABLES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
-- --------------------------------------------------------------------------------------------------------------------------

CREATE SMALLFILE TABLESPACE TBS_ADMINSEC_INDEXES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINsec_INDEXES_1M' 
        SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE TBS_ADMINSEC_TABLES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINsec_TABLES_1M' 
   SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
CREATE  BIGFILE TABLESPACE TBS_ADMINSEC_INDEXES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINsec_INDEXES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE   BIGFILE TABLESPACE TBS_ADMINSEC_TABLES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINsec_TABLES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;    
-- --------------------------------------------------------------------------------------------------------------------------

CREATE SMALLFILE TABLESPACE TBS_ADMINRET_INDEXES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINret_INDEXES_1M' 
        SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE TBS_ADMINRET_TABLES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINret_TABLES_1M' 
   SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
CREATE  BIGFILE TABLESPACE TBS_ADMINRET_INDEXES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINret_INDEXES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE   BIGFILE TABLESPACE TBS_ADMINRET_TABLES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINret_TABLES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;      
-- --------------------------------------------------------------------------------------------------------------------------


CREATE SMALLFILE TABLESPACE TBS_ADMINWKF_INDEXES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINwkf_INDEXES_1M' 
        SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE TBS_ADMINWKF_TABLES_1M 
    DATAFILE 
       '/u01/app/oracle/oradata/XE/DB_TBS_ADMINwkf_TABLES_1M' 
   SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
CREATE  BIGFILE TABLESPACE TBS_ADMINWKF_INDEXES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINwkf_INDEXES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE   BIGFILE TABLESPACE TBS_ADMINWKF_TABLES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINwkf_TABLES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;     
    
    -----------------------------------------------------------------------------
        
        CREATE SMALLFILE TABLESPACE TBS_ADMINOAM_INDEXES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINoam_INDEXES_1M' 
        SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE SMALLFILE TABLESPACE TBS_ADMINOAM_TABLES_1M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINoam_TABLES_1M' 
   SIZE 2097152 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
    
CREATE  BIGFILE TABLESPACE TBS_ADMINOAM_INDEXES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINoam_INDEXES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE   BIGFILE TABLESPACE TBS_ADMINOAM_TABLES_5M 
    DATAFILE 
        '/u01/app/oracle/oradata/XE/DB_TBS_ADMINoam_TABLES_5M' 
    SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;    
